In [1]:
#import numpy and arrays
import numpy as np
import array as ar

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))



[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
arr = np.array([[1,2,3,4],[6,7,8,9]])
print(arr)
print(type(arr))

[[1 2 3 4]
 [6 7 8 9]]
<class 'numpy.ndarray'>


In [5]:
arr = np.array((1,2,3,4,55))
print(arr)

[ 1  2  3  4 55]


In [16]:
a = ar.array('i', [1,2,3])
print(a)
print(type(a))
a = ar.array('f', [1.0,2.0,3.0])
print(a)
print(type(a))

array('i', [1, 2, 3])
<class 'array.array'>
array('f', [1.0, 2.0, 3.0])
<class 'array.array'>


In [29]:
a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [28]:
a = np.logspace(0,10,5)
print(a)
type(a)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]


numpy.ndarray

In [27]:
k = range(1,10)
print(k)
for i in k:
    print(i)

range(1, 10)
1
2
3
4
5
6
7
8
9


In [30]:
for i in 'abcd':
    print(i)

a
b
c
d


In [35]:
a = np.arange(1,10)

for i in a:
    print(i)
type(a)
a

1
2
3
4
5
6
7
8
9


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a = np.full((2,3),5)
a

array([[5, 5, 5],
       [5, 5, 5]])

In [57]:

a = np.array([1,2,3,4])
b = np.sqrt(a)
print(b)
b=np.arcsin(a)
print(b)

[1.         1.41421356 1.73205081 2.        ]
[1.57079633        nan        nan        nan]


C:\Users\Abrarali\AppData\Local\Temp\ipykernel_9300\1888050568.py:4: RuntimeWarning: invalid value encountered in arcsin
  b=np.arcsin(a)


In [90]:
a = np.array([1,2,3,4])
b = np.array([1,3,3,5])

#Comp Function
print(a>=b)
print(a<=b)
print(a>b)
print(a<b)
print(a==b)

# Any function
print(any(a>b))
print(any(a<b))

# Logical Function
print(np.logical_and(a<b,a>b))
print(np.logical_or(a<b,a>b))
print(np.logical_xor(a<b,a>b))
print(np.logical_not(a<b,a>b))

# Where 
c = np.where(a % 2 == 0,a + 1, 0)
print(c)

# Copy method
c = a.copy()
print(c) 

# Dimension of Array
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.shape)
b = a.reshape((2,2))
print(b)
    

[ True False  True False]
[ True  True  True  True]
[False False False False]
[False  True False  True]
[ True False  True False]
False
True
[False False False False]
[False  True False  True]
[False  True False  True]
[ True False  True False]
[0 3 0 5]
[1 2 3 4]
1
4
8
int64
(4,)
[[1 2]
 [3 4]]


In [91]:
print("----- 2.3 Create a 3x3 matrix with values from 0 to 8 -----")
array_1d = np.arange(9)
matrix_3x3 = array_1d.reshape(3, 3)
print("3x3 Matrix:\n", matrix_3x3)
print()


----- 2.3 Create a 3x3 matrix with values from 0 to 8 -----
3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]



In [93]:
print("----- 1.1 Create an array of zeros -----")
zeros_array = np.zeros(10)
print("Array of zeros:", zeros_array)
print()

----- 1.1 Create an array of zeros -----
Array of zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

